name: Deploy to Firebase Hosting

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  FIREBASE_PROJECT_ID: swift-cursor-467917-v4

jobs:
  buildAndDeploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        
    - name: Install Firebase CLI
      run: npm install -g firebase-tools
        
    - name: Build Spring Boot application
      run: |
        chmod +x ./mvnw
        ./mvnw clean package -DskipTests
        
    - name: Create Firebase project directory
      run: |
        mkdir -p firebase-deploy
        cp -r src/main/resources/static/* firebase-deploy/
        cp -r src/main/resources/templates/* firebase-deploy/
        cp target/*.jar firebase-deploy/
        
    - name: Deploy to Firebase
      run: |
        cd firebase-deploy
        firebase deploy --only hosting --project ${{ env.FIREBASE_PROJECT_ID }} --token "${{ secrets.FIREBASE_TOKEN }}"
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
