name: Deploy to Firebase Hosting

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install Firebase CLI
      run: npm install -g firebase-tools
      
    - name: Build Spring Boot application
      run: |
        chmod +x ./mvnw
        ./mvnw clean package -DskipTests
        
    - name: Create Firebase project directory
      run: |
        mkdir -p firebase-deploy
        cp -r src/main/resources/static/* firebase-deploy/
        cp -r src/main/resources/templates/* firebase-deploy/
        cp target/*.jar firebase-deploy/
        
    - name: Deploy to Firebase
      uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: '${{ secrets.GITHUB_TOKEN }}'
        firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
        channelId: live
        projectId: modumomo-modelhouse
